version: "1"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      # database URL
      - FASTAPI_SOUND_RECOMMENDER_DATABASE_URL=postgresql://fastapi_sound_recommender:fastapi_sound_recommender@db:5432/fastapi_sound_recommender
    depends_on:
      - db
    volumes:
      - .:/app
    command: bash -c "gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080"
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_sound_recommender
      - POSTGRES_PASSWORD=fastapi_sound_recommender
      - POSTGRES_DB=fastapi_sound_recommender

volumes:
  postgres_data:
