name: Run Tests
on: push

env:
  FASTAPI_SOUND_RECOMMENDER_DATABASE_URL: sqlite:///fastapi_sound_recommender
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Deps
        run: |
          pip install -r requirements.txt
          pip install httpx
      - name: Run Tests
        run: python3 -m pytest
